#!/usr/bin/env bash
# lib/init.sh — --init wizard logic

# detect_harnesses
# Prints one preset name per line for each preset whose binary is found in $PATH.
# Reads binary field from frontmatter of each .preset file.
detect_harnesses() {
  local f binary preset
  for f in "$WRAPIT_PRESETS_DIR"/*.preset; do
    [ -f "$f" ] || continue
    preset="${f##*/}"
    preset="${preset%.preset}"
    case "$preset" in
      _*) continue ;;
    esac
    binary="$(_parse_frontmatter "$f" "binary")"
    [ -n "$binary" ] || continue
    if command -v "$binary" > /dev/null 2>&1; then
      printf '%s\n' "$preset"
    fi
  done
}

# run_init_gitignore <gitignore_file>
# Asks user whether to add .wrapit to the given .gitignore file.
# Reads answer from stdin. Safe to call non-interactively (EOF = no).
run_init_gitignore() {
  local gitignore_file="$1"

  [ ! -f "$gitignore_file" ] && return 0

  # Already listed — nothing to do
  if grep -q '\.wrapit' "$gitignore_file" 2>/dev/null; then
    return 0
  fi

  printf '\nAdd .wrapit to %s? [y/N] ' "$gitignore_file" >&2
  local answer
  if IFS= read -r answer 2>/dev/null; then
    case "$answer" in
      [Yy]|[Yy][Ee][Ss])
        printf '.wrapit\n' >> "$gitignore_file"
        printf 'Added .wrapit to %s\n' "$gitignore_file" >&2
        ;;
    esac
  fi
}

# _project_specific_section
# Prints a commented-out project-specific bindings template.
_project_specific_section() {
  cat <<'EOF'

# ── Project workspace ──────────────────────────────────────────────────────────
# $PWD is always mounted rw automatically; listed here for clarity.
rw  $PWD

# ── Project-specific bindings ──────────────────────────────────────────────────
# Add paths specific to this project that are not covered by the preset above.
# See README.md for guidance on what to add here.
#
# Examples:
#   rw? ~/.pyenv              # Python version manager
#   rw? ~/.cargo              # Rust toolchain
#   ro  ~/.aws                # AWS credentials (read-only)
EOF
}

# run_init [--preset <name>]
# Writes a .wrapit file to $PWD.
# With --preset: non-interactive, uses the named preset.
# Without --preset: interactive wizard.
run_init() {
  local preset_name=""
  local force=false

  while [ $# -gt 0 ]; do
    case "$1" in
      --preset)
        shift
        preset_name="${1:-}"
        shift
        ;;
      --force)
        force=true
        shift
        ;;
      *)
        shift
        ;;
    esac
  done

  local out_file="$PWD/.wrapit"

  if [ -n "$preset_name" ]; then
    local preset_content
    preset_content="$(get_preset "$preset_name")" || return 1

    if [ -f "$out_file" ] && [ ! -t 0 ]; then
      printf 'wrapit: %s already exists; refusing to overwrite in non-interactive mode\n' \
        "$out_file" >&2
      return 1
    fi

    if [ -f "$out_file" ] && [ -t 0 ]; then
      printf '%s already exists. Overwrite? [y/N] ' "$out_file" >&2
      local ans
      IFS= read -r ans
      case "$ans" in
        [Yy]|[Yy][Ee][Ss]) ;;
        *) printf 'Aborted.\n' >&2; return 1 ;;
      esac
    fi

    {
      printf '# .wrapit — wrapit sandbox configuration\n'
      printf '# Generated by: wrapit --init --preset %s\n' "$preset_name"
      printf '#\n'
      printf '%s\n' "$preset_content"
      _project_specific_section
    } > "$out_file"

    check_wrapit "$out_file" 2>/dev/null || true

    run_init_gitignore "$PWD/.gitignore"

    printf 'Wrote %s\n' "$out_file" >&2
    return 0
  fi

  # Interactive mode
  local detected
  detected="$(detect_harnesses)"

  if [ -n "$detected" ]; then
    printf 'Detected AI harnesses on your PATH:\n' >&2
    printf '%s\n' "$detected" | while IFS= read -r p; do
      printf '  - %s\n' "$p" >&2
    done
  fi

  printf '\nWhich preset would you like to use? [claude-code] ' >&2
  local chosen
  if IFS= read -r chosen 2>/dev/null && [ -n "$chosen" ]; then
    preset_name="$chosen"
  else
    preset_name="$(printf '%s' "$detected" | head -1)"
    [ -z "$preset_name" ] && preset_name="claude-code"
  fi

  run_init --preset "$preset_name"
}
